### ISSUE TITLE
Memory Leak in roc_plot

### ISSUE THREAD

**Issue by ljchang** [canlab/CanlabCore#1]
I've found a weird memory leak in the roc_plot() function when running in single-interval mode and the accuracy is perfect.  Don't have time to figure it out now, but will try and come back later.

``` matlab
binary_outcome = logical([ones(sum(dat.Y==1),1); zeros(sum(dat.Y==3),1)]);
pattern_response = [pexp(dat.Y==3); pexp(dat.Y==1)];

% Single Interval Accuracy
ROC_si = roc_plot(pattern_response, binary_outcome, 'color', 'r');
```

**Comment by torwager** [comment]
add_blobs did not work right with bi-color map option when map has only -1 and 1 values.

**Comment by danweflen** [comment]
@ljchang : Did you ever fix this? Should I fix it or close the issue?

**Comment by ljchang** [comment]
Not sure.  I think it was a pretty specific edge case that won't be encountered frequently.  It would be great if you could fix it.  You might just want to test it to see if it is still an issue.

**Comment by danweflen** [comment]
@ljchang : Do you have the script and data necessary to reproduce the memory leak?

**Comment by ljchang** [comment]
does the one reporting the issue not work anymore?  If not, then maybe it's fixed?
