### ISSUE TITLE
blobs not being displayed on 'full' montage style

### ISSUE THREAD

**Issue by yonestar** [canlab/CanlabCore#12]
Hi,

Nikhil and Tor -- thank you for the new display style functionality!!
When I make a "full" montage, and then add blobs to it from a statistic image, they only show on the axial montage, not on the sagital/surface montages at the top row.  This is true whether I try to add them using addblobs() or with canlab_results_fmri_display()

![figure_4](https://cloud.githubusercontent.com/assets/4513934/10467185/9b516b58-71b5-11e5-88c9-9b483423b0fb.png)

**Comment by torwager** [comment]
thanks - nikhil has fixed, will upload final soon -

**Comment by marsyred** [comment]
Unsure if this is an issue specific to me, but when I try to plot using canlab_results_fmri_display() the blobs do appear on the montage slices (I did not try the 3D surfaces), but I get this error on Matlab 2015a:

Error:
Undefined function or variable "vstr".

Error in render_blobs (line 348)
                if str2double(vstr(1:3))<8.4  % pre R2014b

**Comment by nikhil195** [comment]
Uploaded the changes. Pushed changes to master directly by mistake, sorry! Will add it to my fork and create pull requests from next time.
@yonestar Request you to check if blobs added to surface are correct.
@marsyred Defined 'vstr' globally, please check if the error is resolved.

**Comment by yonestar** [comment]
Hi,
Blobs seem to be added in the correct locations :+1: 
But, the surface plots are ignoring the user's color input parameters (although the slices use them correctly)
thanks!  

example:  i asked to plot blobs in black:

![image](https://cloud.githubusercontent.com/assets/4513934/10562482/9a86ecfc-751b-11e5-94e6-5120e1bf20a5.png)

**Comment by torwager** [comment]
yes, totally.  could you let Nikita know directly too just in case, so he’s sure to get the message?

**Comment by nikhil195** [comment]
Will check.

**Comment by nikhil195** [comment]
Uploaded fix, sorry for the delay. Will add other features related to colours like outline after checking compatibility with cluster_surf.

**Comment by marsyred** [comment]
Hey! I'm trying to add an outline to an ROI plotted with canlab_results_fmridisplay, but when I add the additional options to addblobs, like so:

o2 = addblobs(o2, region(hesch_mask_dat), 'color', [1 1 1], 'outline', 'linewidth', 1, 'smooth');

I get the following error:
Undefined variable "images" or class "images.internal.migrateImshowSettings".

Error in iptgetpref (line 24)
    images.internal.migrateImshowSettings();

Error in imfilter>useIPPL (line 299)
    prefFlag = iptgetpref('UseIPPL');

Error in imfilter>filterPartOrWhole (line 351)
ippFlag  = useIPPL(a,outSize,h,nonzero_h);

Error in imfilter (line 163)
  b_tmp = filterPartOrWhole(a, out_size_row, hrow, start, sameSize, convMode);

Error in render_blobs (line 339)
                Z = imfilter(Z, PSF, 'replicate', 'conv');

Error in fmridisplay/addblobs (line 185)
    [blobhan, cmaprange, mincolor, maxcolor] = render_blobs(currentmap, obj.montage{i}, obj.SPACE,
    varargin{:});



----

I have three related follow up questions - Is it possible to selectively plot an outline of an ROI on another activation map? And/or can I selectively change the transparency of a single addblobs layer?

When I do:
transparency_change(o2,.5)

It changes the transparency of all displayed data.

Finally, where's the significance threshold bar for the color map? I'm assuming I'm overlooking an easy option on this one.

Thanks!

**Comment by yonestar** [comment]
Hi,

To add layers of different transparency, use the options:   'trans',
'transvalue', .3

for example

o1 = addblobs(o1, region(tspecific), 'splitcolor', {[1 0 0] [.5 0 0] purp
purp}, 'trans', 'transvalue', 0, 'outline');

Because transvalue is 0 and I specified outline, it plots a transparent
outline only


This is not currently implemented for the surface view, I think

Yoni
