### ISSUE TITLE
writing statistic_images in MNI space

### ISSUE THREAD

**Issue by yonestar** [canlab/CanlabCore#14]
Writing them to disk with the 'mni' flag creates rings of zero and near-zero values around positive activation clusters.  Here is the same image written to disk with and without the 'mni' flag, and then re-loaded:

![image](https://cloud.githubusercontent.com/assets/4513934/12280307/367c8794-b94a-11e5-86cf-d21cf24afd38.png)
![image](https://cloud.githubusercontent.com/assets/4513934/12280309/40c00122-b94a-11e5-8488-1d7c72ed329e.png)

To reproduce:  I'm attaching a sample file that can be loaded in as a statistic_image, written to disk with and without the 'mni' flag, and then reloaded
[tspecific.nii.gz](https://github.com/canlab/CanlabCore/files/88151/tspecific.nii.gz)

**Comment by danweflen** [comment]
I'll check it out. I'm still new to the canlab tools, so if anyone else has experience with this I would appreciate your help.

**Comment by danweflen** [comment]
What does the mni flag mean?

**Comment by wanirepo** [comment]
I knew this problem before. 'mni' flag involves "resampling" the image's
space into mni space. When it does resampling, it uses interpolation, and
it creates some near-zero values.

There are multiple methods in interpolation (e.g., in matlab, 'nearest',
'linear', 'spline', 'cubic'), and you could try different methods.

Or if possible, don't use the 'mni' flag. As far as I know, the 'mni'
option has been implemented (by Luka) to make it easy to visualize the
images in fslview, which can only take a specific type of space. The canlab
tools and many other tools (e.g., mricrogl) don't have that specific
requirement (if I'm right).

One more thing: even when you don't use 'mni' option, your image should be
in the mni space if you did preprocessing correctly. But the way of image
construction (e.g., what is the cubic space dimension for the whole brain,
etc.) could be different.

Best,
Wani

On Wed, Jan 13, 2016 at 2:13 PM, Daniel Weflen <notifications@github.com>
wrote:

> What does the mni flag mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/canlab/CanlabCore/issues/14#issuecomment-171434443>.
>



-- 
Choong-Wan (Wani) Woo
Web <http://wanirepo.github.io/> | Code <https://github.com/wanirepo/> | Google
Scholar <https://scholar.google.com/citations?user=fZLY5H8AAAAJ&hl=en&oi=ao>
| Lab <http://wagerlab.colorado.edu/>
PhD candidate
Cognitive and Affective Neuroscience Lab
University of Colorado Boulder

**Comment by pkragel** [comment]
Interpolation is definitely the issue. I agree with Wani that you probably don't need to use the 'MNI' flag.


If you want to change your voxel size to match that of brainmask.nii (basically what the 'MNI' flag is doing), you can resample your image with resample_space.m and then threshold. This should avoid interpolation 'smearing' for voxels near the cutoff.


Phil

________________________________

**Comment by yonestar** [comment]
Thanks a lot guys, this is really helpful.

I solved the issue by using nearest neighbor interpolation when writing
statistic_images to disk in MNI space (instead of the default linear
interpolation); nearest neighbor will not make near-zero "rings" around
activations.

Phil, your solution would have been just as good --  except it fails
because of a bug in the code.  I will open a new issue for this bug, and
mark the issue in this thread as closed.
