### ISSUE TITLE
bug in resample_space() for statistic_images

### ISSUE THREAD

**Issue by yonestar** [canlab/CanlabCore#15]
Hi,

Statistic_images crash when attempting to resample_space():
![image](https://cloud.githubusercontent.com/assets/4513934/12315614/2cab5254-ba3a-11e5-9a65-d5a5192673c5.png)

This is in fact a semi-known issue, at least to Wani and me (but has not been officially logged).  For example, image_vector.write() will resample the image space when the MNI flag is passed in.  And, if the input to write() is a statistic_image, we first cast it to fmri_data before resampling the space -- because resampling the space of a statistic_image crashes.

Also:  I think it would be super helpful to have a brief write up of how we are storing image space parameters (i.e., a description of volInfo, the image "mask", etc.) -- and why statistic_image does this differently, apparently.

Thanks
Yoni

**Comment by torwager** [comment]
Thanks - there are a couple of ways of resampling…maybe statistic_image has it’s own method.  we have to handle some specific fields. it should apply the .sig field to write  thresholded map(s) if thresholding has been applied.  maybe there is a problem with statistic_image’s method, and we should go back to copying what is in fmri_data but handling specific fields.

maybe this is something that nikita could look into? Or you two could get together?

Thanks,
Tor

**Comment by nikhil195** [comment]
Closing the issue as it hasn't been encountered again and cannot be reproduced. Please open if the error occurs again.
