### ISSUE TITLE
Finding canlab preproc

### ISSUE THREAD

**Issue by ARTeed** [canlab/CanlabCore#17]
Hello Canlab,

I'm looking forward to using core tools for my data but have searched through the canlab repository and can't find any of the preproc scripts. Have the names been changed or have they not been added to the repository? I use spm12 or 8. I appreciate your time!

**Comment by danweflen** [comment]
The preproc scripts have not been added to the repository.

**Comment by danweflen** [comment]
We've added a new public "preprocess" repo. It has all of our preprocessing code, feel free to use it!
