### ISSUE TITLE
concatenation of runs and regressors

### ISSUE THREAD

**Issue by inej** [canlab/CanlabCore#18]
Hi, 

A quick question about design matrix: when running the GLM, is it better to concatenate the data (various runs), the movement regressors, the wm and csf avg. signal in the matrix?

**Comment by yonestar** [comment]
Hi,

I think it may be better not to concatenate the nuisance regressors across
runs.  For example, its possible that effects of head motion will differ
between runs at a given voxel, I think.

We often concatenate the regressors of interest across runs, though it
should not matter much whether you do that or not.

Best
Yoni

**Comment by danweflen** [comment]
Has this problem been solved? Or did we decide that it was better not to modify the code?

**Comment by sgeuter** [comment]
if you concatenate regressors across runs, you will to manually adjust the highpass filtering and AR model. that would be something to manually after SPM design specification and before design estimation.
