### ISSUE TITLE
Too may image names in command window

### ISSUE THREAD

**Issue by esalman** [canlab/CanlabCore#21]
https://github.com/canlab/CanlabCore/blob/f37ea6491add6d5afbc940411268e64455e5eb33/CanlabCore/Data_extraction/load_image_set.m#L196
This is printing all image names in output, maybe print first 10 only?

**Comment by danweflen** [comment]
Does it make it harder to debug, or does it look bad when used with publish()? I don't want to accidentally cause other problems while fixing this.

**Comment by esalman** [comment]
I didn't try publish(), it's just that I am working with 500+ images and it is printing all of them on the command window. But it is a minor issue and probably not worth changing.

**Comment by torwager** [comment]
Hi Salman,

That is kind of a feature that I don't want to change as the default option at the moment. But it would make sense to add a noverbose option invoked by a keyword entry of the same name during the call to the function. If it doesn't exist already. Would that work?

More generally, how is it going? I added a couple of additional things to the set of Atlas images at some point in the last week or so.

It would be great to get a prototype version working soon! I think we are close based on what we did together.

Tor

**Comment by esalman** [comment]
Hello, I guess no need to change this, since it is not related to neurosynth_feature_labels function anyhow.

I was working on anatomical and functional feature labels functions; I have a qual exam coming up this week so there's been little progress but I'll share the results with you once I'm done with the exam. Thanks!

**Comment by torwager** [comment]
There should be a 'noverbose' option now!
