### ISSUE TITLE
Compatible with recent versions of Matlab

### ISSUE THREAD

**Issue by thinault** [canlab/CanlabCore#26]
Hi everyone,
I would like to run 'scn_spm_design_check.m', but I am getting a lot of error like 'Undefined function or variable 'getvif''. Is it because of the version of SPM(12) or Matlab (17b) I use?

Thanks
Thomas

**Comment by torwager** [comment]
Hi Thomas, SPM12 and Matlab2017b should work just fine.  
'Undefined function or variable' usually means that a required file is not on your matlab path. You can fix that by "adding with subfolders" to your path.  getvif is here:
GitHub/CanlabCore/CanlabCore/OptimizeDesign11/core_functions/getvif.m

See the function canlab_toolbox_setup in the CanlabCore repo (https://github.com/canlab/CanlabCore), and the walkthrough here:
https://canlab.github.io/_pages/canlab_help_1_installing_tools.html

We're adding more help at https://canlab.github.io.  

Hope this helps!
Tor

**Comment by thinault** [comment]
Thanks a lot !

-- 
Thomas Hinault, Ph.D
Postdoctoral Researcher _ Courtney Lab
Department of Psychological and Brain Sciences
Johns Hopkins University
https://www.researchgate.net/profile/Thomas_Hinault
