### ISSUE TITLE
onsets2fmridesign: error in script due to changes in Matlab

### ISSUE THREAD

**Issue by sandrushba** [canlab/CanlabCore#34]
Dear Canlab team, 

since I've been working with this script recently, I just wanted to point out to you that the current version of the function onsets2fmridesign doesn't work (at least in recent Matlab versions, I'm using Matlab R2019b). The reason seems to be a change in the function _pad_ which has been changed to _padarray_ (see also here: https://github.com/fordanic/image-registration/issues/6)

If I replace 'pad' with 'padarray' in line 456, the function works just fine. I think this could be helpful for future users.

Thanks.

Best wishes
Sandra

**Comment by torwager** [comment]
Thanks! I’ve made that change.

Best wishes,
Tor
____________________________________
Tor Wager
Diana L. Taylor Distinguished Professor
Presidential Cluster in Neuroscience and 
Department of Psychological and Brain Sciences
Dartmouth College
___________________________________
