### ISSUE TITLE
What was rationale for moving external toolboxes to the private repository?

### ISSUE THREAD

**Issue by ljchang** [canlab/CanlabCore#4]
It was nice for users outside of the laboratory to be able to use our toolboxes since there is no documentation about dependencies anywhere.  I had checked the licenses for all of the toolboxes that were in the external folder and it seemed like we were allowed to redistribute as long as it was noted who developed the toolbox and where we acquired it.

I don't really care either way, but someone should create documentation for installing the CanlabCore repository and include a list of dependent toolboxes and where they can be downloaded.

**Comment by ljchang** [comment]
Lasso - http://www.stat.berkeley.edu/~yugroup/downloads/  
-(notes: rename lasso.m -> lasso_rocha.m)

Spider - http://people.kyb.tuebingen.mpg.de/spider/download_frames.html

matlab graph library - https://www.cs.purdue.edu/homes/dgleich/packages/matlab_bgl/

**Comment by yonestar** [comment]
makes sense to me to include all dependencies in CanlabCore, to make it
easy for our users.

Downsides I can think of:  1) CanlabCore will take up more space (another
50 mb);  2) users might already have these toolboxes installed and don't
want redundant/conflicting copies

but ease of use for the majority of users might outweigh those cons and
favor inclusion in CanlabCore

Thanks for pointing this out Luke, I'll try to bring up at lab mtg if there
is a minute

**Comment by torwager** [comment]
Hi, if we are allowed to redistribute then it's totally fine with me to put them back in core. I was just trying to separate out other peoples stuff but if it is OK to redistribute them let's put it back

Cheers,
Tor

**Comment by ljchang** [comment]
Just double checked again.  We are fine to redistribute all three of these libraries as long as we aren't using them for commercial purposes.  Happy to keep them separate though if you think the file size is too big and/or it will create conflicts for most users.

Lasso - permission to redistribute
Spider: GPLv3
Matlab BGL: "Matlab code: BSD libmbgl code: GPLv2" from github

**Comment by yonestar** [comment]
I moved the external tools into CanlabCore, so that it now comes with all
its dependencies.  Thanks Luke for pointing this out.

We all need to do the same matlab path routine:

   1. rmpath(genpath( <path to canlab core > ))
   2. rmpath(genpath( <path to canlab private > ))
   3. sync those two repos
   4. addpath(genpath( <path to canlab core > ))
   5. addpath(genpath( <path to canlab private > ))


sorry the hassle.  there might be a few more times that we need to do this
as we transition

**Comment by ljchang** [comment]
Great, thanks Yoni!  I'm going to mark this as closed.
