### ISSUE TITLE
Legend for Wager Combined atlas FSL

### ISSUE THREAD

**Issue by kteh123** [canlab/CanlabCore#48]
Hi

I'm wondering if there are any legend information regarding the 489 regions in the combined 2018 atlas. So I want to use this atlas in FSL however the index are numbers 1-489. Are there any corresponding labels somewhere? Thank you.

Kevin

**Comment by torwager** [comment]
Hi Kevin,Yes, there are labels stored in the .labels property of the Matlab object.  You could expert those to a text file for use with FSL or other tools.TorSent from my iPhoneOn Jun 29, 2023, at 11:32 AM, Kevin Teh ***@***.***> wrote:﻿
Hi
I'm wondering if there are any legend information regarding the 489 regions in the combined 2018 atlas. So I want to use this atlas in FSL however the index are numbers 1-489. Are there any corresponding labels somewhere? Thank you.
Kevin

**Comment by kteh123** [comment]
Thank you so much for your help.
