### ISSUE TITLE
Missing brainmask.nii

### ISSUE THREAD

**Issue by ljchang** [canlab/CanlabCore#7]
I am configuring a new computer and can't seem to find the brainmask.nii file, which is the default mask used by fmri_data().  Should we put this somewhere in the repository (e.g., canlab_canonical_brains or External)?  or put a note on where to get it?  I have spm12 and spm8 and it doesn't seem to be in the canonical folder anymore.

I'm going to put it in canlab_canonical_brains for now, but feel free to move it.

**Comment by ljchang** [comment]
I found it in spm8/apriori, but it's only in spm12 in the fieldmap toolbox, which I typically exclude as a lot of their functions conflict with default matlab ones.

**Comment by torwager** [comment]
Yes I think adding it to our repository is a good idea in light of it's moving around in S p.m.
