### ISSUE TITLE
preprocessing before using mediation_toolbox

### ISSUE THREAD

**Issue by nedakaboodvand** [canlab/CanlabCore#8]
Hi
I have a question regarding mediation toolbox. I want to see whether time series related to region "M" in the brain is mediating the relation between time-series related to region "X" and region "Y"! Actually, I am not sure which preprocesing steps are necessary! In my case, Time-Series are scaled to percent signal change. In addition I have used detrending, mean centering, and despiking before running mediation function. The problem is that the values for X->M and M->Y and X->Y are not in line with correlation values between related signals! I understand that they are coefficients for multiple regression analysis but again they should be similar to correlation results! Therefore I just want to make sure which preprocessing steps are essential.
Thank you for your time.
Best Regards,
Neda

**Comment by torwager** [comment]
That preprocessing sounds reasonable, Neda.  The values for the slopes (path coefficients) may not be similar to the correlations, because the correlation normalizes by the variance estimate and the slope does not.
Tor

**Comment by nedakaboodvand** [comment]
Great! Thank you very much for this quick response!
Best Regards,
Sincerely,
Neda
